apiVersion: v1
kind: Service
metadata: 
  name: management_law
  labels: 
    app: management_law
spec:
  ports: 
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector: 
    app: management_law
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: management_law
  labels: 
    app: management_law
spec:
  replicas: 1
  selector:
    matchLabels:
      app: management_law
  template:
    metadata:
      labels:
        app: management_law
    spec:
      containers:
      - image: onesslimani/management_law:v1
        name: management_law
        env: 
        - name: MANAGEMENT_LAW_LANG
          value: "pt_BR"
        - name: MYSQL_HOST
          value: "root"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: "sms"
        - name: MYSQL_PASSWORD
          value: ""
        ports:
        - containerPort: 80
          name: management_law
